### ISSUE TITLE
Unable to install ezstructure

### ISSUE THREAD

**Issue by marcobon96** [Jerrythafast/ezstructure#1]
Hello, I'm trying to install ezstructure and this is the output:

```
Collecting ezstructure
  Using cached ezstructure-1.0.1.tar.gz (22 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in ./mambaforge/envs/serpe/lib/python3.11/site-packages (from ezstructure) (1.24.2)
Collecting scipy (from ezstructure)
  Obtaining dependency information for scipy from https://files.pythonhosted.org/packages/b8/46/1d255bb55e63de02f7b2f3a2f71b59b840db21d61ff7cd41edbfc2da448a/scipy-1.11.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached scipy-1.11.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (59 kB)
Using cached scipy-1.11.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (36.2 MB)
Building wheels for collected packages: ezstructure
  Building wheel for ezstructure (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for ezstructure (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [196 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/ezstructure
      copying ezstructure/io.py -> build/lib.linux-x86_64-cpython-311/ezstructure
      copying ezstructure/__init__.py -> build/lib.linux-x86_64-cpython-311/ezstructure
      copying ezstructure/structure.py -> build/lib.linux-x86_64-cpython-311/ezstructure
      copying ezstructure/distruct.py -> build/lib.linux-x86_64-cpython-311/ezstructure
      copying ezstructure/chooseK.py -> build/lib.linux-x86_64-cpython-311/ezstructure
      creating build/lib.linux-x86_64-cpython-311/ezstructure/vars
      copying ezstructure/vars/__init__.py -> build/lib.linux-x86_64-cpython-311/ezstructure/vars
      copying ezstructure/vars/allelefreq.pxd -> build/lib.linux-x86_64-cpython-311/ezstructure/vars
      copying ezstructure/vars/admixprop.pxd -> build/lib.linux-x86_64-cpython-311/ezstructure/vars
      copying ezstructure/vars/admixprop.h -> build/lib.linux-x86_64-cpython-311/ezstructure/vars
      copying ezstructure/vars/marglikehood.h -> build/lib.linux-x86_64-cpython-311/ezstructure/vars
      copying ezstructure/vars/allelefreq.h -> build/lib.linux-x86_64-cpython-311/ezstructure/vars
      running build_ext
      /tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-p_2nf1e1/ezstructure_599fb8c833a84d499640900ede3cabb9/ezstructure/vars/utils.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      Compiling ezstructure/vars/utils.pyx because it changed.
      [1/1] Cythonizing ezstructure/vars/utils.pyx
      building 'ezstructure.vars.utils' extension
      creating build/temp.linux-x86_64-cpython-311
      creating build/temp.linux-x86_64-cpython-311/ezstructure
      creating build/temp.linux-x86_64-cpython-311/ezstructure/vars
      gcc -pthread -B /home/marcob/mambaforge/envs/serpe/compiler_compat -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/marcob/mambaforge/envs/serpe/include -fPIC -O2 -isystem /home/marcob/mambaforge/envs/serpe/include -fPIC -I/tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/numpy/core/include -I/home/marcob/mambaforge/envs/serpe/include/python3.11 -c ezstructure/vars/utils.c -o build/temp.linux-x86_64-cpython-311/ezstructure/vars/utils.o
      In file included from /tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/numpy/core/include/numpy/ndarraytypes.h:1929,
                       from /tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                       from /tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                       from ezstructure/vars/utils.c:1106:
      /tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
         17 | #warning "Using deprecated NumPy API, disable it with " \
            |  ^~~~~~~
      gcc -pthread -B /home/marcob/mambaforge/envs/serpe/compiler_compat -shared -Wl,--allow-shlib-undefined -Wl,-rpath,/home/marcob/mambaforge/envs/serpe/lib -Wl,-rpath-link,/home/marcob/mambaforge/envs/serpe/lib -L/home/marcob/mambaforge/envs/serpe/lib -Wl,--allow-shlib-undefined -Wl,-rpath,/home/marcob/mambaforge/envs/serpe/lib -Wl,-rpath-link,/home/marcob/mambaforge/envs/serpe/lib -L/home/marcob/mambaforge/envs/serpe/lib build/temp.linux-x86_64-cpython-311/ezstructure/vars/utils.o -o build/lib.linux-x86_64-cpython-311/ezstructure/vars/utils.cpython-311-x86_64-linux-gnu.so
      /tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-p_2nf1e1/ezstructure_599fb8c833a84d499640900ede3cabb9/ezstructure/vars/admixprop.pxd
        tree = Parsing.p_module(s, pxd, full_module_name)

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      import numpy as np
      cimport numpy as np
      cimport allelefreq as af
              ^
      ------------------------------------------------------------

      ezstructure/vars/admixprop.pxd:3:8: 'allelefreq.pxd' not found

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef np.ndarray alpha, var, xi
          cdef list oldvar

          cdef copy(self)
          cdef require(self)
          cdef update(self, np.ndarray[np.uint8_t, ndim=2] G, af.AlleleFreq pi)
                                                              ^
      ------------------------------------------------------------

      ezstructure/vars/admixprop.pxd:26:56: 'AlleleFreq' is not a type identifier

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef list oldvar

          cdef copy(self)
          cdef require(self)
          cdef update(self, np.ndarray[np.uint8_t, ndim=2] G, af.AlleleFreq pi)
          cdef square_update(self, np.ndarray[np.uint8_t, ndim=2] G, af.AlleleFreq pi)
                                                                     ^
      ------------------------------------------------------------

      ezstructure/vars/admixprop.pxd:27:63: 'AlleleFreq' is not a type identifier

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              """

              self.var = np.require(self.var, dtype=np.float64, requirements='C')
              self.xi = np.require(self.xi, dtype=np.float64, requirements='C')

          cdef update(self, np.ndarray[np.uint8_t, ndim=2] G, af.AlleleFreq pi):
                                                              ^
      ------------------------------------------------------------

      ezstructure/vars/admixprop.pyx:58:56: 'AlleleFreq' is not a type identifier

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              else:
                  self.var = self.alpha + self.var
                  self.xi = np.exp(digamma(self.var)-digamma(utils.insum(self.var,[1])))
              self.require()

          cdef square_update(self, np.ndarray[np.uint8_t, ndim=2] G, af.AlleleFreq pi):
                                                                     ^
      ------------------------------------------------------------

      ezstructure/vars/admixprop.pyx:84:63: 'AlleleFreq' is not a type identifier

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  pi : instance of `AlleleFreq`

              """

              self.var = np.zeros((self.N,self.K), dtype=np.float64)
              Q_update(<np.uint8_t*>G.data, <double*> pi.zetabeta.data, <double*> pi.zetagamma.data, <double*> self.xi.data, <double*> self.var.data, self.N, pi. L, self.K)
                                            ^
      ------------------------------------------------------------

      ezstructure/vars/admixprop.pyx:74:38: Python objects cannot be cast to pointers of primitive types

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  pi : instance of `AlleleFreq`

              """

              self.var = np.zeros((self.N,self.K), dtype=np.float64)
              Q_update(<np.uint8_t*>G.data, <double*> pi.zetabeta.data, <double*> pi.zetagamma.data, <double*> self.xi.data, <double*> self.var.data, self.N, pi. L, self.K)
                                                                        ^
      ------------------------------------------------------------

      ezstructure/vars/admixprop.pyx:74:66: Python objects cannot be cast to pointers of primitive types
      Compiling ezstructure/vars/admixprop.pyx because it changed.
      [1/1] Cythonizing ezstructure/vars/admixprop.pyx
      Traceback (most recent call last):
        File "/home/marcob/mambaforge/envs/serpe/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/marcob/mambaforge/envs/serpe/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/marcob/mambaforge/envs/serpe/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 416, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 24, in <module>
        File "/tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 346, in run
          self.run_command("build")
        File "/tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/Cython/Distutils/build_ext.py", line 122, in build_extension
          new_ext = cythonize(
                    ^^^^^^^^^^
        File "/tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-0qfn83c1/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: ezstructure/vars/admixprop.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ezstructure
Failed to build ezstructure
ERROR: Could not build wheels for ezstructure, which is required to install pyproject.toml-based projects
```
I'm running Ubuntu 22.04.2 LTS on WSL2 on Windows 11.
Python version=3.11.0
Wheel version=0.41.0
Numpy version=1.24.2

Thank you

**Comment by Jerrythafast** [comment]
Hi!

Yikes, looks like the build is broken on the brand-new Cython 3.0. The easiest way for me to help you out quickly is the following:

```bash
# Explicitly install our build dependencies first:
pip install --upgrade setuptools wheel "numpy>=1.19.0" "cython>=0.29.21,<3.0.0"

# Then install ezstructure without build isolation:
pip install --no-build-isolation ezstructure
```

Please let me know if that helps!

In the meantime, to fix this issue I'll see if I can [migrate to Cython3](https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html); if that takes too long I'll probably just release a `1.0.2` that explicitly depends on an earlier version.

**Comment by marcobon96** [comment]
This solution works fine, thank you!
